In [6]:
import pandas as pd
import requests


# URL of our endpoint
URL = "https://2krjwwbp8d.execute-api.us-east-1.amazonaws.com/prod/hello"


# read the testfile
df = pd.read_csv('data/data_10000.csv', sep=',')
# Cleaning data dropping any row with any null value
df.dropna(axis=0, how='any', inplace=True)
data = df.copy()

In [7]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
9995,537224,22622,BOX OF VINTAGE ALPHABET BLOCKS,2.0,12/5/2010 16:24,9.95,13174.0,United Kingdom
9996,537224,22623,BOX OF VINTAGE JIGSAW BLOCKS,2.0,12/5/2010 16:24,4.95,13174.0,United Kingdom
9997,537224,21363,HOME SMALL WOOD LETTERS,2.0,12/5/2010 16:24,4.95,13174.0,United Kingdom
9998,537224,21556,CERAMIC STRAWBERRY MONEY BOX,2.0,12/5/2010 16:24,2.55,13174.0,United Kingdom
9999,537224,22497,SET OF 2 TINS VINTAGE BATHROOM,2.0,12/5/2010 16:24,4.25,13174.0,United Kingdom

In [8]:
data.shape

(7616, 8)

In [9]:
data = data[:7000]

In [10]:
data.shape

(7000, 8)

In [ ]:
df.to_csv('data/data_7000.csv', index=False)

In [ ]:

# write a single row from the testfile into the api
#export = data.loc[2].to_json()
#response = requests.post(URL, data = export)
# print(response)

# write all the rows from the testfile to the api as put request
for i in data.index:
    try:
        # convert the row to json
        export = data.loc[i].to_json()

        # send it to the api
        response = requests.post(URL, data=export)

        # print the returncode
        print(export)
        print(response)
    except:
        print(data.loc[i])